### PR TITLE
Add support for string based paths etc

### PR DESCRIPTION
**Pull request by seertenedos**
This also includes a change for the nuget feed to come from a build variable.

Basically this time i separated it out into separate interface and classes so you can pick the implementation you want. I was going to add it to the base class but it would have been too messy.

### CODE REVIEW

**Comment by seertenedos** [comment]
also this is more to get feedback because i honestly hate how i have jsut added SP to the end of the classes/interfaces but i could not think of a good name change for them and just when with SP for string path. 

There may also be a better way to do the conversion to string.

**Comment by tmds** [comment]
I'm thinking, add a class that derives from `FuseFileSystemBase` to avoid the duplication/maintenance cost.

Something like:
```c#
    public class FuseFileSystemStringBase : FuseFileSystemBase
    {
        public static new string RootPath => "/";

        private readonly Encoding _pathEncoding;

        public FuseFileSystemStringBase(Encoding encoding)
        {
            _pathEncoding = encoding ?? throw new ArgumentNullException(nameof(encoding));
        }

        private unsafe string ToString(ReadOnlySpan<byte> span)
        {
            fixed(byte* ptr = span)
            {
                return _pathEncoding.GetString(ptr, span.Length);
            }
        }

        public virtual int ChMod(string path, mode_t mode, FuseFileInfoRef fiRef)
            => -ENOSYS;

        public override int ChMod(ReadOnlySpan<byte> path, mode_t mode, FuseFileInfoRef fiRef)
            => ChMod(ToString(path), mode, fiRef);

        // ...
    }
```
Do you think that would work?

**Comment by seertenedos** [comment]
I thought of that but was thinking that with the number of methods it would be confusing when you implement it to see 2 copies of each method and knowing you only need to override one and if you override one the other does not get called. That said it does solve the naming issue so can change it to be that style.

**Comment by seertenedos** [comment]
closing this and opened a cleaner pull request

**Comment by tmds** [comment]
Overriding one should be enough to make it work.
Probably it makes sense to make the string-based overloads _protected_ instead of _public_. This forces any direct user to use the _Span_ methods provided by _IFuseFileSystem_.

**Pull request closed without merging**
