### PR TITLE
String path and publish fix

### PR DESCRIPTION
**Pull request by seertenedos**
Cleaned up the change to just have the 3 changes.
1. Fix for nuget feed to come from variable on build server
2. Added new base class with the string version of path etc
3. Added VS2019 solution file for those that want it

### CODE REVIEW

**Comment by seertenedos** [comment]
Also if i have missed any methods or any properties that you think should be string please let me know or just change it. I was guessing a few of them

**Comment by tmds** [comment]
Copying from https://github.com/tmds/Tmds.Fuse/pull/25#issuecomment-517438033:

> Overriding one should be enough to make it work.
Probably it makes sense to make the string-based overloads protected instead of public. This forces any direct user to use the Span methods provided by IFuseFileSystem

**Comment by seertenedos** [comment]
That is true though i have now hit something that does not work well. I want to have a version that logs every entry/exit basically a way of seeing what is coming in and out when you have issues etc in my own use of this. If it was an interface that just gets called and not a base class that is easy. In my case now i just put the interface in my own app and basically have an implementation for the base that calls that interface that is the same as the interface you have but string based and in that class that extends the base it logs the request and response based on logging level.  That said feels a bit like a hack.  Tried log weaving but the spans break the free options out there.

**Comment by tmds** [comment]
It would be good if the library can do some logging. I haven't added any. My thoughts are to add some properties to MountOptions, and then log from the FuseMount class when logging is enabled. wdyt?

**Comment by seertenedos** [comment]
That could also work but then you would need to do the same string conversions the base i build does as logging bytes for filenames etc likely will not be that useful for most people. For the moment i have my logging working now and it is just a matter of making sure i have everything that should be a string as a string.

**Pull request merged**
